### ISSUE TITLE
Further insight upon how DB Evolve is used as part of a database versioning strategy 

### ISSUE THREAD

**Issue by jonathanmach** [keredson/peewee-db-evolve#54]
Hi all!

I just wanted to gain further insight upon how DB Evolve has been used in production and how are you usually versioning the migrations.
Do you normally use the SQL script generated by DB Evolve to create a new migration file (delta-script) so as to keep the history of all the migrations?
So, I'm assuming that in this scenario `db.evolve()` is not generally  used in production, is that correct? 

It would be great to hear some experiences from the community. Thank you in advance!

**Comment by keredson** [comment]
We definitely used it in production.  Daily deploy script for 3 years at least. There was always a human running the script to eyeball it, but I can't remember any instances where that was necessary, I'm just cautious with deploys.

A previous incantation of this (for Django) I wrote a layer of hashed known good database signatures and let it build a DAG of known good upgrades, and if the diff didn't match that it wouldn't run.  But I don't think anyone ever actually used it.  (Even myself. 😅)

**Comment by jonathanmach** [comment]
Hi @keredson, I hope you're well. Thanks so much for your response and for sharing your experience.

So, how do you usually handle schema changes that also require data changes (ie. changing the datatype of a column) using `db.evolve()`?
Is it a multi-step procedure that would involve something like: creating a new field in the model, running `db.evolve()`, then executing a script to convert the data and add it to the column; then, lastly, deleting the old field and running `db.evolve()`?

Thanks for your support!

**Comment by keredson** [comment]
Depends.  If pg can handle the type change automatically, the table isn't so huge writes would be blocked for more than a few seconds, and the software could handle both types or it was tolerable to have a few seconds of a feature being broken, then we'd just do it live.  (Server restart for us was the next step after evolve and near instant.). This wound up being quite common.  (Remember pg can do schema changes in a transaction.)

But yes, if those didn't apply a multi step was taken.  Code change to handle both schemas and column add, bespoke script to migrate, column delete and code cleanup.

The most common hurdle we hit was adding column defaults on big tables.  Pg had to copy the data to each row which could take a long time.  But I read that's fixed in 11 or 12 I think?

**Comment by jonathanmach** [comment]
Hi @keredson, thanks very much. That's really helpful.

I have been studying a couple of db schema migration strategies involving peewee-db-evolve and you helped me to have a better understanding of how it's currently been used.

Again, thanks very much!
